use core::f64;

use crate::{
    game::{
        entities::{
            DUMMY_HP, DUMMY_SIZE, ENEMY_HP, ENEMY_SIZE, EXPLODED_RED_BARREL_HP, EXPLODED_RED_BARREL_SIZE, Entity, EntityType, PROJECTILE_HP, RED_BARREL_HP, RED_BARREL_SIZE, WEAK_ENEMY_MULTIPLICATOR
        },
        map::Point,
    },
    render::RendererData,
};

pub fn generate_entities(
    entity_type: EntityType,
    position: Point,
    height: f64,
    facing_direction: f64,
    renderer_data: &RendererData,
) -> Option<Entity> {
    match entity_type {
        EntityType::PlayerBullet => Entity::new(
            position,
            0.0,
            height,
            1.0,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::PlayerBullet,
            PROJECTILE_HP,
            1.0,
        ),
        EntityType::EnemyBullet => Entity::new(
            position,
            0.0,
            height,
            1.0,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::EnemyBullet,
            PROJECTILE_HP,
            1.0,
        ),
        EntityType::PlayerArrow => Entity::new(
            position,
            0.0,
            height,
            1.0,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::PlayerArrow,
            PROJECTILE_HP,
            1.0,
        ),
        EntityType::EnemyArrow => Entity::new(
            position,
            0.0,
            height,
            1.0,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::EnemyArrow,
            PROJECTILE_HP,
            1.0,
        ),
        EntityType::Dummy => Entity::new(
            position,
            0.0,
            height,
            DUMMY_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::Dummy,
            DUMMY_HP,
            DUMMY_SIZE,
        ),
        EntityType::RangedEnemy => Entity::new(
            position,
            0.0,
            height,
            ENEMY_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::RangedEnemy,
            ENEMY_HP,
            ENEMY_SIZE,
        ),
        EntityType::Archer => Entity::new(
            position,
            0.0,
            height,
            ENEMY_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::Archer,
            ENEMY_HP,
            ENEMY_SIZE,
        ),
        EntityType::MeleeEnemy => Entity::new(
            position,
            0.0,
            height,
            ENEMY_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::MeleeEnemy,
            ENEMY_HP,
            ENEMY_SIZE,
        ),
        EntityType::SummonerEnemy => Entity::new(
            position,
            0.0,
            height,
            ENEMY_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::SummonerEnemy,
            ENEMY_HP,
            ENEMY_SIZE,
        ),
        EntityType::WeakEnemy => Entity::new(
            position,
            0.0,
            0.0,
            ENEMY_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::WeakEnemy,
            ENEMY_HP * WEAK_ENEMY_MULTIPLICATOR,
            ENEMY_SIZE,
        ),
        EntityType::RedBarrel => Entity::new(
            position,
            0.0,
            height,
            RED_BARREL_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::RedBarrel,
            RED_BARREL_HP,
            RED_BARREL_SIZE,
        ),
        EntityType::ExplodedRedBarrel => Entity::new(
            position,
            0.0,
            height,
            RED_BARREL_SIZE,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::ExplodedRedBarrel,
            EXPLODED_RED_BARREL_HP,
            EXPLODED_RED_BARREL_SIZE,
        ),
        _ => Entity::new(
            position,
            0.0,
            height,
            1.0,
            facing_direction,
            entity_type.get_default_texture_id(),
            renderer_data,
            EntityType::Dummy,
            DUMMY_HP,
            DUMMY_SIZE,
        ),
    }
}
